/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.view.frames;

import javax.swing.JFrame;
import ni.edu.uni.programacion.view.panels.PnlVehicle;

/**
 *
 * @author LENOVO 17
 */
public class VehicleApp extends javax.swing.JFrame {

    /**
     * Creates new form VehicleApp
     */
    public VehicleApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dpContent = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mniVehicle = new javax.swing.JMenuItem();
        mniNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehiculos");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(6, 6));
        setPreferredSize(new java.awt.Dimension(671, 522));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        dpContent.setPreferredSize(new java.awt.Dimension(665, 516));

        javax.swing.GroupLayout dpContentLayout = new javax.swing.GroupLayout(dpContent);
        dpContent.setLayout(dpContentLayout);
        dpContentLayout.setHorizontalGroup(
            dpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dpContentLayout.setVerticalGroup(
            dpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(dpContent, gridBagConstraints);

        jMenu2.setText("Opciones");

        mniVehicle.setText("Catalogo");
        mniVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVehicleActionPerformed(evt);
            }
        });
        jMenu2.add(mniVehicle);

        mniNew.setText("New");
        mniNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewActionPerformed(evt);
            }
        });
        jMenu2.add(mniNew);
        jMenu2.add(jSeparator1);

        mniQuit.setText("Exit");
        jMenu2.add(mniQuit);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        setBounds(0, 0, 687, 583);
    }// </editor-fold>//GEN-END:initComponents

    private void mniVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVehicleActionPerformed
        // TODO add your handling code here:
        IFrmVehicle iFrmVehicle = new IFrmVehicle();
        
        dpContent.add(iFrmVehicle);
        iFrmVehicle.setVisible(true);
    }//GEN-LAST:event_mniVehicleActionPerformed

    private void mniNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewActionPerformed
        // TODO add your handling code here:
        PnlVehicle pnlvehicle=new PnlVehicle();
        dpContent.add(pnlvehicle);
        pnlvehicle.setVisible(true);
    }//GEN-LAST:event_mniNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpContent;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mniNew;
    private javax.swing.JMenuItem mniQuit;
    private javax.swing.JMenuItem mniVehicle;
    // End of variables declaration//GEN-END:variables
}
